# Generated by Django 4.1.5 on 2023-02-04 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
        ('nominations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nomination',
            name='election',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='elections.election'),
        ),
    ]
