# Generated by Django 4.1.5 on 2023-01-22 16:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='election',
            name='createdAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='election',
            name='updatedAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
