# Generated by Django 4.1.3 on 2022-12-03 02:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voting', '0003_voting_voter_alter_voting_contestant'),
    ]

    operations = [
        migrations.AddField(
            model_name='nomination',
            name='campaign_name',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='voting',
            name='voter',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voter', to=settings.AUTH_USER_MODEL),
        ),
    ]
