# Generated by Django 4.1.3 on 2023-01-14 04:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0004_nomination_campaign_name_alter_voting_voter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(null=True)),
                ('createdAt', models.DateField(auto_now=True)),
                ('updatedAt', models.DateField(auto_now_add=True)),
                ('startAt', models.DateTimeField()),
                ('duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio', models.CharField(choices=[('P', 'President'), ('M', 'Minister'), ('MP', 'Parliamentarian'), ('H', 'Head Of State'), ('D', 'DCE')], max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='voting',
            name='votes',
        ),
        migrations.AddField(
            model_name='nomination',
            name='createdAt',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='nomination',
            name='updatedAt',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nomination',
            name='portfolio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='voting.portfolio'),
        ),
    ]
