# Generated by Django 4.1.3 on 2023-01-14 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0005_election_portfolio_remove_voting_votes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='voting.nomination')),
            ],
        ),
    ]
