# Generated by Django 4.1.3 on 2023-01-17 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voting', '0006_candidate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='nomination',
            name='campaign_name',
        ),
        migrations.RemoveField(
            model_name='nomination',
            name='description',
        ),
        migrations.AddField(
            model_name='election',
            name='endAt',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='category',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='election',
            field=models.ForeignKey(default='exit', on_delete=django.db.models.deletion.CASCADE, to='voting.election'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='election',
            name='createdAt',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio',
            field=models.CharField(choices=[('P', 'President'), ('M', 'Minister'), ('MP', 'Parliamentarian'), ('H', 'Head Of State'), ('D', 'DCE')], default='', max_length=3, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='voting',
            name='contestant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contestant', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='voting',
            name='voter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='voter', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
    ]
